# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.20.2"
"rocks-config.nvim" = "1.3.1"
"rocks-git.nvim" = "1.4.0"

"plenary.nvim" = "scm"
nvim-treesitter = "0.9.2"
"mason.nvim" = { version = "1.10.0", opt = true }
"mason-lspconfig.nvim" = { version = "1.27.0", opt = true }
nvim-lspconfig = "0.1.7"
"none-ls.nvim" = { git = "nvimtools/none-ls.nvim" }
"mason-null-ls.nvim" = { git = "jay-babu/mason-null-ls.nvim" }
luasnip = "2.2.0"
"lspkind.nvim" = "scm"
cmp_luasnip = { git = "saadparwaiz1/cmp_luasnip"}
cmp-nvim-lsp = { git = "hrsh7th/cmp-nvim-lsp"}
cmp-buffer = { git = "hrsh7th/cmp-buffer" }
cmp-path = { git = "hrsh7th/cmp-buffer" }
nvim-cmp = { git = "hrsh7th/nvim-cmp" }

rustaceanvim = { version = "4.21.0", opt = true}

"mini.base16" = "0.9.0"
"which-key.nvim" = "1.6.0"
"todo-comments.nvim" = { version = "1.2.0", opt = true}
"better-escape.nvim" = "scm"
nvim-highlight-colors = { git = "brenoprata10/nvim-highlight-colors" }
"telescope.nvim" = { version = "scm" }
"heirline.nvim" = { version = "1.0.3" }
nvim-autopairs = { version = "scm" }
"gitsigns.nvim" = { git = "lewis6991/gitsigns.nvim" }
"aerial.nvim" = { git = "stevearc/aerial.nvim" }
"comment.nvim" = "0.8.0"
"toggleterm.nvim" = { version = "2.10.0", opt = true }
"neo-tree.nvim" = { version = "3.14", opt = true }
nvim-web-devicons = { version = "0.99", opt = true }

[config]
plugins_dir = "plugins/"
auto_setup = true
